apiVersion: v1
kind: Service
metadata:
  name: sunny-days-ahead
  namespace: opsera-sunny-days-ahead-dev
  labels:
    app: sunny-days-ahead
    tenant: opsera
spec:
  type: ClusterIP
  selector:
    app: sunny-days-ahead
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
