apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-sunny-days-ahead-dev

resources:
  - ../../base

labels:
  - includeSelectors: false
    pairs:
      environment: dev
      managed-by: opsera-c2c

replicas:
  - name: sunny-days-ahead
    count: 2

images:
  - name: PLACEHOLDER_ECR_URI
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/sunny-days-ahead
    newTag: e43b08a-20260217055151
